# ESPHome Culligan Water Softener BLE Client
# Uses custom component for Culligan CS Meter Soft water softeners
#
# Device: ESP32-S3 DevKitC-1

substitutions:
  device_name: watersoftener-ble
  friendly_name: "Water Softener"
  # Water Softener MAC Address
  water_softener_mac: "E8:3B:AA:91:CD:68"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  on_boot:
    priority: -100
    then:
      - logger.log: "Water Softener BLE Client Starting..."
  platformio_options:
    board_build.mcu: esp32s3
    board_build.variant: esp32s3
    board_build.flash_mode: dio

esp32:
  board: seeed_xiao_esp32s3
  variant: ESP32S3
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      # Enable Bluetooth with Bluedroid stack
      CONFIG_BT_ENABLED: y
      CONFIG_BT_BLUEDROID_ENABLED: y
      CONFIG_BT_BLE_ENABLED: y
      CONFIG_BTDM_CTRL_MODE_BLE_ONLY: y
      CONFIG_BTDM_CTRL_MODE_BR_EDR_ONLY: n
      CONFIG_BTDM_CTRL_MODE_BTDM: n
      # GATT client support
      CONFIG_BT_GATTC_ENABLE: y
      # Connection parameters
      CONFIG_BT_ACL_CONNECTIONS: "3"
      CONFIG_BT_BLE_50_FEATURES_SUPPORTED: y

# Enable logging (reduce for production)
logger:
  level: INFO
  logs:
    culligan_water_softener: INFO
    esp32_ble_tracker: WARN
    esp32_ble_client: WARN

# Enable Home Assistant API
api:
  encryption:
    key: !secret ha_api_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: false
  power_save_mode: none
  manual_ip:
    static_ip: 192.168.1.177
    gateway: 192.168.1.254
    subnet: 255.255.255.0
    dns1: 192.168.50.1
  ap:
    ssid: "${device_name} Fallback"
    password: !secret fallback_password

time:
  - platform: homeassistant
    id: homeassistant_time

# Add safe_mode for OTA recovery
safe_mode:
  num_attempts: 3

# BLE Tracker for scanning
esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 110ms
    active: true

# BLE Client for Water Softener
ble_client:
  - mac_address: ${water_softener_mac}
    id: culligan_ble_client
    on_connect:
      then:
        - logger.log: "Connected to Water Softener!"
    on_disconnect:
      then:
        - logger.log: "Disconnected from Water Softener"

# External component - local path
external_components:
  - source:
      type: git
      url: https://github.com/jtubb/esphome-culligan-water-softener
      ref: main
    components: [ culligan_water_softener ]

# Water softener component
culligan_water_softener:
  id: water_softener
  ble_client_id: culligan_ble_client
  password: 1234  # Default password
  poll_interval: 60s

# Sensors
sensor:
  - platform: culligan_water_softener
    culligan_water_softener_id: water_softener
    # Real-time sensors
    current_flow:
      name: "${friendly_name} Current Flow"
      id: current_flow
    soft_water_remaining:
      name: "${friendly_name} Soft Water Remaining"
      id: soft_water_remaining
    water_usage_today:
      name: "${friendly_name} Water Usage Today"
      id: water_usage_today
    peak_flow_today:
      name: "${friendly_name} Peak Flow Today"
      id: peak_flow_today
    water_hardness:
      name: "${friendly_name} Water Hardness"
      id: water_hardness
    brine_level:
      name: "${friendly_name} Salt Level"
      id: brine_level
    avg_daily_usage:
      name: "${friendly_name} Average Daily Usage"
      id: avg_daily_usage
    days_until_regen:
      name: "${friendly_name} Days Until Regeneration"
      id: days_until_regen
    battery_level:
      name: "${friendly_name} Battery"
      id: battery_level
    # Lifetime totals
    total_gallons:
      name: "${friendly_name} Total Gallons Treated"
      id: total_gallons
    total_regenerations:
      name: "${friendly_name} Total Regenerations"
      id: total_regenerations
    # Resettable counters
    total_gallons_resettable:
      name: "${friendly_name} Total Gallons (Resettable)"
      id: total_gallons_resettable
    total_regenerations_resettable:
      name: "${friendly_name} Total Regens (Resettable)"
      id: total_regens_resettable
    # Settings sensors
    reserve_capacity:
      name: "${friendly_name} Reserve Capacity"
      id: reserve_capacity
    resin_capacity:
      name: "${friendly_name} Resin Capacity"
      id: resin_capacity
    regen_day_override:
      name: "${friendly_name} Regen Day Override"
      id: regen_day_override
    # Brine tank sensors
    brine_tank_capacity:
      name: "${friendly_name} Brine Tank Capacity"
      id: brine_tank_capacity
    brine_salt_percent:
      name: "${friendly_name} Salt Level Percent"
      id: brine_salt_percent
    low_salt_alert:
      name: "${friendly_name} Low Salt Alert Threshold"
      id: low_salt_alert
    # Filter/air sensors
    filter_backwash_days:
      name: "${friendly_name} Filter Backwash Days"
      id: filter_backwash_days
    air_recharge_days:
      name: "${friendly_name} Air Recharge Days"
      id: air_recharge_days
    air_recharge_frequency:
      name: "${friendly_name} Air Recharge Frequency"
      id: air_recharge_frequency
    # Cycle time sensors (positions 1-4)
    backwash_time:
      name: "${friendly_name} Backwash Time"
      id: backwash_time
    brine_draw_time:
      name: "${friendly_name} Brine Draw Time"
      id: brine_draw_time
    rapid_rinse_time:
      name: "${friendly_name} Rapid Rinse Time"
      id: rapid_rinse_time
    brine_refill_time:
      name: "${friendly_name} Brine Refill Time"
      id: brine_refill_time
    # Cycle positions 5-8
    cycle_position_5:
      name: "${friendly_name} Cycle Position 5"
      id: cycle_pos_5
    cycle_position_6:
      name: "${friendly_name} Cycle Position 6"
      id: cycle_pos_6
    cycle_position_7:
      name: "${friendly_name} Cycle Position 7"
      id: cycle_pos_7
    cycle_position_8:
      name: "${friendly_name} Cycle Position 8"
      id: cycle_pos_8

  # WiFi signal sensor
  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal"
    update_interval: 60s

# Text sensors
text_sensor:
  - platform: culligan_water_softener
    culligan_water_softener_id: water_softener
    firmware_version:
      name: "${friendly_name} Firmware Version"
      id: firmware_version
    device_time:
      name: "${friendly_name} Device Time"
      id: device_time
    regeneration_time:
      name: "${friendly_name} Regeneration Time"
      id: regen_time

# Binary sensors (status flags)
binary_sensor:
  - platform: culligan_water_softener
    culligan_water_softener_id: water_softener
    display_off:
      name: "${friendly_name} Display Off"
      id: display_off
    bypass_active:
      name: "${friendly_name} Bypass Active"
      id: bypass_active
    shutoff_active:
      name: "${friendly_name} Shutoff Active"
      id: shutoff_active
    regeneration_active:
      name: "${friendly_name} Regenerating"
      id: regen_active
    rental_regen_disabled:
      name: "${friendly_name} Rental Regen Disabled"
      id: rental_regen_disabled
    rental_unit:
      name: "${friendly_name} Rental Unit"
      id: rental_unit
    prefill_enabled:
      name: "${friendly_name} Pre-fill Enabled"
      id: prefill_enabled
    prefill_soak_mode:
      name: "${friendly_name} Pre-fill Soak Mode"
      id: prefill_soak_mode

# Buttons (commands)
button:
  - platform: culligan_water_softener
    culligan_water_softener_id: water_softener
    regenerate_now:
      name: "${friendly_name} Regenerate Now"
      id: regen_now_btn
    regenerate_next:
      name: "${friendly_name} Regenerate Next Scheduled"
      id: regen_next_btn
    sync_time:
      name: "${friendly_name} Sync Time"
      id: sync_time_btn
    reset_gallons:
      name: "${friendly_name} Reset Gallons Counter"
      id: reset_gallons_btn
    reset_regenerations:
      name: "${friendly_name} Reset Regenerations Counter"
      id: reset_regens_btn

  # Restart button
  - platform: restart
    name: "${friendly_name} Restart"

# Switches (toggles)
switch:
  - platform: culligan_water_softener
    culligan_water_softener_id: water_softener
    display:
      name: "${friendly_name} Display"
      id: display_switch

# Numbers (adjustable settings)
# Note: Values display as floats (32.0) - this is controlled by Home Assistant UI
number:
  - platform: culligan_water_softener
    culligan_water_softener_id: water_softener
    water_hardness:
      name: "${friendly_name} Set Water Hardness"
      id: set_hardness
    regeneration_time_hour:
      name: "${friendly_name} Set Regen Hour"
      id: set_regen_hour
    reserve_capacity:
      name: "${friendly_name} Set Reserve Capacity"
      id: set_reserve
    salt_level:
      name: "${friendly_name} Set Salt Level"
      id: set_salt_level
    regen_days:
      name: "${friendly_name} Set Regen Days"
      id: set_regen_days
    resin_capacity:
      name: "${friendly_name} Set Resin Capacity"
      id: set_resin_capacity
    prefill_duration:
      name: "${friendly_name} Set Prefill Duration"
      id: set_prefill_duration
    backwash_time:
      name: "${friendly_name} Set Backwash Time"
      id: set_backwash_time
    brine_draw_time:
      name: "${friendly_name} Set Brine Draw Time"
      id: set_brine_draw_time
    rapid_rinse_time:
      name: "${friendly_name} Set Rapid Rinse Time"
      id: set_rapid_rinse_time
    brine_refill_time:
      name: "${friendly_name} Set Brine Refill Time"
      id: set_brine_refill_time
    low_salt_alert:
      name: "${friendly_name} Set Low Salt Alert"
      id: set_low_salt_alert
